//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public string RequestSubject { get; set; }
        public int RequestTypeId { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> RequestDepartment { get; set; }
        public string RequestCabinet { get; set; }
        public int PriorityId { get; set; }
        public int RequestStatusId { get; set; }
        public int DeviceId { get; set; }
        public int UserId { get; set; }
        public System.DateTime RequestDateOfCreation { get; set; }
        public System.DateTime RequestDateLastUpdate { get; set; }
        public Nullable<System.DateTime> RequestClosingDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Device Device { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual RequestType RequestType { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual User User { get; set; }
    }
}
